* Requirements

R001:	If Caller A and caller B are in a stable two party telephone call and caller C calls caller A and caller A hasn’t disable call waiting,  then caller A shall hear the notify beep and caller B should not hear the notify beep and caller C should hear normal ringing.
R002:	If Caller A and caller B are in a stable two party telephone call and caller C calls caller A and caller A has disabled call waiting,  then caller A shall not hear the notify beep and caller B should not hear the notify beep and caller C should hear normal ringing.
R003:	If Caller A and caller B are in a stable two party telephone call and caller C calls caller A and caller A hasn’t disable call waiting and put caller B on hold to answer caller C, then caller A shall not hear the notify beep and caller B should not hear anything and caller C should hear caller A.
R004: If Caller A and Caller C are in a stable two party telephone call after
Caller A switched from talking to Caller B in order to talk to Caller C, then
Caller A shall go back to talking to Caller B if Caller C hangs up.
R005: If Caller A and Caller C are in a stable two party telephone call after
Caller A switched from talking to Caller B in order to talk to Caller C, then
Caller A shall be able to switch back to talking to Caller B without hanging up
on Caller C.


* Setup
For all tests we will need the following setup:
** Software and hardware installation for call routing server
All software for the release being tested is installed on the server responsible for call routing.
Run "validate_routing_install.sh" in the "~/test" folder when logged in as the "routing" user.
This should print out "Test Successful".

** Phone Setup
Four installed telephones will be required for testing.
  - Caller A_enabled (555-0001) is provisioned and has call waiting enabled.
  - Caller A_disabled (555-0002) is provisioned and has call waiting disabled.
  - Caller B (555-0010) is provisioned.
  - Caller C (555-0020) is provisioned.

* Teardown
To tear down after a test, disconnect all phones involved by hanging up.

* Test Cases

* Justification Paragraphs and lame excuses for not using SE Tools
We are doing lab 4 to help us understand how to create good requirements, and test cases for a real world situation.
It teaches us to ensure that the requirements and test cases cover every situation that the call waiting can have so
that the system will have the best software quality possible. This lab helps us to go through the process from
creating the requirements in the test document and actually creating the test cases base on the requirements.

Dillon Hiatt

Dylan Jones:
On 10/18/2013 I forgot to punch in to SE Tools until after I started working.

Justification Paragraph:
We are doing lab 4 to get more experience in creating good requirements and
writing test documents.  With a call waiting example, we are able to take a
simple system and use it as practice.  Being to write good requirements and the
test document are invaluable when it comes to quality software.  A major part
of the test document is the test cases, which are useful for the testing that
must be done in order to assure the quality of a software system.
